- hosts: all
  become: true
  become_user: root
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/frontend-deployment.yml --kubeconfig=/home/ubuntu/.kube/config
      ignore_errors: true
    - name: delete old service
      command: kubectl delete -f /home/ubuntu/frontend-service.yml --kubeconfig=/home/ubuntu/.kube/config
      ignore_errors: true
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/frontend-deployment.yml --kubeconfig=/home/ubuntu/.kube/config
    - name: create new service
      command: kubectl apply -f /home/ubuntu/frontend-service.yml --force --kubeconfig=/home/ubuntu/.kube/config