apiVersion: v1
kind: Service
metadata:
  name: ai-author-reactjs-service
spec:
  selector:
    app: ai-author-reactjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
